services:
  portfolio:
    build:
      context: .
    container_name: portfolio
    image: portfolio
    restart: unless-stopped
    working_dir: /usr/src/app
    networks:
      - proxy
    labels:
      labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.portfolio.rule: Host(`${TRAEFIK_PORTFOLIO}`)
      traefik.http.routers.portfolio.entrypoints: https
      traefik.http.routers.portfolio.tls: true
      traefik.http.routers.portfolio.tls.certresolver: letsencrypt

networks:
  proxy:
    external: true
